<!doctype html>

<head>

<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
<meta name="description" content="">
<meta name="author" content="">

<title>Registeration</title>
	
<script src="../bower_components/angular/angular.min.js"></script>
<script src="../bower_components/angular-route/angular-route.min.js"></script>
<script src="../js/passScript.js"></script>
</head>

<body ng-app="validationApp" ng-controller="mainController">

<form name="userForm" class="form-horizontal" method = "POST" action = "index.php/register" onsubmit="return register();" ng-submit="submitForm(userForm.$valid)" novalidate>
<fieldset>

<!-- Form Name -->
<legend style="text-align: center">IFind Registration</legend>

<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="firstname">First Name <span style="color:red">*</span></label>  
  <div class="col-md-4">
  <input id="firstname" name="firstname" type="text" placeholder="Jane" class="form-control input-md" ng-model="user.fname" type="text" placeholder="" class="form-control input-md" required="">  
  </div>
</div>

<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="lastname">Last Name <span style="color:red">*</span></label>  
  <div class="col-md-4">
  <input id="lastname" name="lastname" type="text" placeholder="Doe" class="form-control input-md" ng-model="user.lname" type="text" placeholder="" class="form-control input-md" required="">
  </div>
</div>

<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="username">Username <span style="color:red">*</span></label>  
  <div class="col-md-4">
  <input id="username" name="username" type="text" placeholder="example908" class="form-control input-md" ng-model-options="{ updateOn: 'blur' }" ng-model="user.username" ng-minlength="3" ng-maxlength="8" required="">
  <p ng-show="userForm.username.$error.minlength" class="help-block">Username is too short.</p>
  <p ng-show="userForm.username.$error.maxlength" class="help-block">Username is too long.</p>
  </div>
</div>

<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="email">Email <span style="color:red">*</span> </label>  
  <div class="col-md-4">
  <input id="email" name="email" placeholder="janedoe@domain.com" class="form-control input-md" ng-model-options="{ updateOn: 'blur' }" ng-model="user.email" type="email" placeholder="johnDoe@example.com" class="form-control input-md" required="">
  <p ng-show="userForm.email.$error.email" class="help-block" >Invalid Email Address</p>    
  </div>
</div>

<!-- Password input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="password">Password <span style="color:red">*</span> </label>
  <div class="col-md-4">
    <input id="password" name="password" type="password" placeholder="" class="form-control input-md" data-ng-model="user.password" ng-minlength="8" ng-maxlength="25" required="">
    <p ng-show="userForm.password.$error.minlength" class="help-block">Password is too short.</p>
  <p ng-show="userForm.password.$error.maxlength" class="help-block">Password is too long.</p>
  </div>
</div>

<!-- Password input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="password2">Confirm Password <span style="color:red">*</span> </label>
  <div class="col-md-4">
    <input id="password2" name="password2" type="password" placeholder="" class="form-control input-md" ng-model-options="{ updateOn: 'blur' }" ng-model="user.password2" required data-password-verify="user.password" required="">
  <p ng-show="userForm.password2.$error.passwordVerify" class="help-block">Passwords do not match </p>
    
  </div>
</div>

<!-- Button -->
<div class="form-group">
  <label class="col-md-4 control-label" for="Submit"></label>
  <div class="col-md-4">
    <button id="saveBnt" name="saveBnt" class="btn btn-primary btn-block" type ="submit" ng-disabled="userForm.$invalid">Submit</button>
  </div>
</div>

</fieldset>
</form>
  </div>
    </div>
</div>
<!--footer -->
  <div class="footer">
    <p> &copy; IFind 2017 </p>
  </div>
<body>
</html>